// VulkanSpike — throwaway SwiftPM package (vulkan-spike/, fully separate
// from swift/Package.swift — see that file's header comment for why)
// proving the two unknowns from the intel-mac-vulkan-backend spike:
//
//   Unknown 1 (shader build step): a GLSL compute shader compiled to
//   SPIR-V with glslc and embedded as a checked-in C++ byte array
//   (spirv_embed.h, generated by scripts/spike-embed-spirv.sh) — no
//   build-time toolchain dependency, following the same "generate once
//   at vendor time" strategy as ggml-metal-embed.cpp.
//
//   Unknown 2 (no-Homebrew-at-runtime distribution): this binary links
//   libMoltenVK.a STATICALLY (see vulkan-spike/Package.swift
//   linkerSettings) and calls Vulkan entry points (vkCreateInstance,
//   etc.) that resolve directly into the statically-linked MoltenVK
//   code — NOT through libvulkan.1.dylib / the Vulkan loader / an ICD
//   JSON. There is no `vkGetInstanceProcAddr` loader indirection here:
//   MoltenVK itself implements the standard Vulkan C ABI, so linking it
//   statically is sufficient. `otool -L` on the built binary should
//   show only system frameworks (Metal, IOSurface, IOKit, AppKit,
//   QuartzCore, Foundation, CoreFoundation, CoreGraphics, libobjc,
//   libc++, libSystem) — no /usr/local/... Homebrew paths. Verified by
//   hiding the Homebrew Vulkan install and re-running the binary; see
//   the spike's commit message for the full write-up.
//
// This is NOT wired into the real whisper_cpp/Parakey targets and does
// not affect them. It is a standalone proof of mechanism only.

#include <vulkan/vulkan.h>

#include <cstdio>
#include <cstdlib>
#include <cstring>
#include <vector>

#include "spirv_embed.h"

#define VK_CHECK(x)                                                          \
    do {                                                                     \
        VkResult _res = (x);                                                 \
        if (_res != VK_SUCCESS) {                                            \
            fprintf(stderr, "FAIL: %s returned %d at %s:%d\n", #x, _res,     \
                    __FILE__, __LINE__);                                     \
            return 1;                                                        \
        }                                                                    \
    } while (0)

static uint32_t find_memory_type(VkPhysicalDevice phys, uint32_t type_bits,
                                  VkMemoryPropertyFlags props) {
    VkPhysicalDeviceMemoryProperties mem_props;
    vkGetPhysicalDeviceMemoryProperties(phys, &mem_props);
    for (uint32_t i = 0; i < mem_props.memoryTypeCount; i++) {
        if ((type_bits & (1u << i)) &&
            (mem_props.memoryTypes[i].propertyFlags & props) == props) {
            return i;
        }
    }
    return UINT32_MAX;
}

int main() {
    printf("=== VulkanSpike: MoltenVK static-link + SPIR-V embed proof ===\n");

    // --- Unknown 2: create a VkInstance via the statically-linked
    // MoltenVK, no loader/ICD involved. ---
    VkApplicationInfo app_info{};
    app_info.sType = VK_STRUCTURE_TYPE_APPLICATION_INFO;
    app_info.pApplicationName = "VulkanSpike";
    app_info.apiVersion = VK_API_VERSION_1_2;

    const char *instance_exts[] = {
        VK_KHR_PORTABILITY_ENUMERATION_EXTENSION_NAME,
        VK_KHR_GET_PHYSICAL_DEVICE_PROPERTIES_2_EXTENSION_NAME,
    };

    VkInstanceCreateInfo inst_info{};
    inst_info.sType = VK_STRUCTURE_TYPE_INSTANCE_CREATE_INFO;
    inst_info.pApplicationInfo = &app_info;
    inst_info.flags = VK_INSTANCE_CREATE_ENUMERATE_PORTABILITY_BIT_KHR;
    inst_info.enabledExtensionCount = 2;
    inst_info.ppEnabledExtensionNames = instance_exts;

    VkInstance instance = VK_NULL_HANDLE;
    VkResult r = vkCreateInstance(&inst_info, nullptr, &instance);
    if (r != VK_SUCCESS) {
        fprintf(stderr,
                "vkCreateInstance failed (%d) with portability flag; "
                "retrying without it\n",
                r);
        inst_info.flags = 0;
        inst_info.enabledExtensionCount = 0;
        VK_CHECK(vkCreateInstance(&inst_info, nullptr, &instance));
    }
    printf("PASS: vkCreateInstance (statically-linked MoltenVK)\n");

    uint32_t dev_count = 0;
    VK_CHECK(vkEnumeratePhysicalDevices(instance, &dev_count, nullptr));
    if (dev_count == 0) {
        fprintf(stderr, "FAIL: no physical devices enumerated\n");
        return 1;
    }
    std::vector<VkPhysicalDevice> devices(dev_count);
    VK_CHECK(vkEnumeratePhysicalDevices(instance, &dev_count, devices.data()));

    VkPhysicalDevice phys = devices[0];
    VkPhysicalDeviceProperties props{};
    vkGetPhysicalDeviceProperties(phys, &props);
    printf("PASS: enumerated %u device(s); using \"%s\"\n", dev_count,
           props.deviceName);

    // Find a compute-capable queue family.
    uint32_t qf_count = 0;
    vkGetPhysicalDeviceQueueFamilyProperties(phys, &qf_count, nullptr);
    std::vector<VkQueueFamilyProperties> qfs(qf_count);
    vkGetPhysicalDeviceQueueFamilyProperties(phys, &qf_count, qfs.data());
    uint32_t compute_qf = UINT32_MAX;
    for (uint32_t i = 0; i < qf_count; i++) {
        if (qfs[i].queueFlags & VK_QUEUE_COMPUTE_BIT) {
            compute_qf = i;
            break;
        }
    }
    if (compute_qf == UINT32_MAX) {
        fprintf(stderr, "FAIL: no compute queue family\n");
        return 1;
    }

    float queue_priority = 1.0f;
    VkDeviceQueueCreateInfo qci{};
    qci.sType = VK_STRUCTURE_TYPE_DEVICE_QUEUE_CREATE_INFO;
    qci.queueFamilyIndex = compute_qf;
    qci.queueCount = 1;
    qci.pQueuePriorities = &queue_priority;

    const char *device_exts[] = {"VK_KHR_portability_subset"};
    // portability_subset is required by MoltenVK devices but only if
    // supported; check support first.
    uint32_t ext_count = 0;
    vkEnumerateDeviceExtensionProperties(phys, nullptr, &ext_count, nullptr);
    std::vector<VkExtensionProperties> exts(ext_count);
    vkEnumerateDeviceExtensionProperties(phys, nullptr, &ext_count, exts.data());
    bool has_portability_subset = false;
    for (auto &e : exts) {
        if (strcmp(e.extensionName, "VK_KHR_portability_subset") == 0) {
            has_portability_subset = true;
        }
    }

    VkDeviceCreateInfo dci{};
    dci.sType = VK_STRUCTURE_TYPE_DEVICE_CREATE_INFO;
    dci.queueCreateInfoCount = 1;
    dci.pQueueCreateInfos = &qci;
    if (has_portability_subset) {
        dci.enabledExtensionCount = 1;
        dci.ppEnabledExtensionNames = device_exts;
    }

    VkDevice device = VK_NULL_HANDLE;
    VK_CHECK(vkCreateDevice(phys, &dci, nullptr, &device));
    printf("PASS: vkCreateDevice\n");

    VkQueue queue;
    vkGetDeviceQueue(device, compute_qf, 0, &queue);

    // --- Unknown 1: load our embedded SPIR-V (compiled offline by
    // scripts/spike-embed-spirv.sh) into a shader module. ---
    VkShaderModuleCreateInfo smci{};
    smci.sType = VK_STRUCTURE_TYPE_SHADER_MODULE_CREATE_INFO;
    smci.codeSize = g_vecadd_spv_len * sizeof(uint32_t);
    smci.pCode = g_vecadd_spv;
    VkShaderModule shader = VK_NULL_HANDLE;
    VK_CHECK(vkCreateShaderModule(device, &smci, nullptr, &shader));
    printf("PASS: vkCreateShaderModule (embedded vecadd.spv, %zu words)\n",
           g_vecadd_spv_len);

#if VULKAN_SPIKE_HAVE_REAL_GGML_SHADER
    {
        // Also prove that a REAL ggml-vulkan shader (compiled via the
        // real upstream vulkan-shaders-gen tool + glslc, not our own
        // placeholder GLSL) produces valid, loadable SPIR-V on this
        // toolchain. We only prove module *creation* here, not a full
        // dispatch — replicating ggml's exact push-constant layout
        // (fastdiv "magic number" constants computed by
        // init_fastdiv_values in ggml-vulkan.cpp) for a real op is
        // real-implementation work, out of scope for this mechanism
        // spike.
        VkShaderModuleCreateInfo real_smci{};
        real_smci.sType = VK_STRUCTURE_TYPE_SHADER_MODULE_CREATE_INFO;
        real_smci.codeSize = g_real_ggml_cpy_f32_f32_spv_len * sizeof(uint32_t);
        real_smci.pCode = g_real_ggml_cpy_f32_f32_spv;
        VkShaderModule real_shader = VK_NULL_HANDLE;
        VK_CHECK(vkCreateShaderModule(device, &real_smci, nullptr, &real_shader));
        printf("PASS: vkCreateShaderModule (REAL ggml cpy_f32_f32.spv, %zu words)\n",
               g_real_ggml_cpy_f32_f32_spv_len);
        vkDestroyShaderModule(device, real_shader, nullptr);
    }
#else
    printf("SKIP: real ggml shader module test (spirv_embed.h built without "
           "GGML_VULKAN_SHADERS_GEN — see spike-embed-spirv.sh)\n");
#endif

    // --- Descriptor set layout: 3 storage buffers (a, b, c) ---
    VkDescriptorSetLayoutBinding bindings[3]{};
    for (int i = 0; i < 3; i++) {
        bindings[i].binding = i;
        bindings[i].descriptorType = VK_DESCRIPTOR_TYPE_STORAGE_BUFFER;
        bindings[i].descriptorCount = 1;
        bindings[i].stageFlags = VK_SHADER_STAGE_COMPUTE_BIT;
    }
    VkDescriptorSetLayoutCreateInfo dslci{};
    dslci.sType = VK_STRUCTURE_TYPE_DESCRIPTOR_SET_LAYOUT_CREATE_INFO;
    dslci.bindingCount = 3;
    dslci.pBindings = bindings;
    VkDescriptorSetLayout dsl;
    VK_CHECK(vkCreateDescriptorSetLayout(device, &dslci, nullptr, &dsl));

    VkPushConstantRange pcr{};
    pcr.stageFlags = VK_SHADER_STAGE_COMPUTE_BIT;
    pcr.offset = 0;
    pcr.size = sizeof(uint32_t);

    VkPipelineLayoutCreateInfo plci{};
    plci.sType = VK_STRUCTURE_TYPE_PIPELINE_LAYOUT_CREATE_INFO;
    plci.setLayoutCount = 1;
    plci.pSetLayouts = &dsl;
    plci.pushConstantRangeCount = 1;
    plci.pPushConstantRanges = &pcr;
    VkPipelineLayout pipeline_layout;
    VK_CHECK(vkCreatePipelineLayout(device, &plci, nullptr, &pipeline_layout));

    VkPipelineShaderStageCreateInfo stage{};
    stage.sType = VK_STRUCTURE_TYPE_PIPELINE_SHADER_STAGE_CREATE_INFO;
    stage.stage = VK_SHADER_STAGE_COMPUTE_BIT;
    stage.module = shader;
    stage.pName = "main";

    VkComputePipelineCreateInfo cpci{};
    cpci.sType = VK_STRUCTURE_TYPE_COMPUTE_PIPELINE_CREATE_INFO;
    cpci.stage = stage;
    cpci.layout = pipeline_layout;
    VkPipeline pipeline;
    VK_CHECK(vkCreateComputePipelines(device, VK_NULL_HANDLE, 1, &cpci, nullptr,
                                       &pipeline));
    printf("PASS: vkCreateComputePipelines\n");

    // --- Buffers: N floats each for a, b, c ---
    const uint32_t N = 1024;
    const VkDeviceSize buf_size = N * sizeof(float);

    VkBuffer buffers[3];
    VkDeviceMemory memories[3];
    for (int i = 0; i < 3; i++) {
        VkBufferCreateInfo bci{};
        bci.sType = VK_STRUCTURE_TYPE_BUFFER_CREATE_INFO;
        bci.size = buf_size;
        bci.usage = VK_BUFFER_USAGE_STORAGE_BUFFER_BIT;
        bci.sharingMode = VK_SHARING_MODE_EXCLUSIVE;
        VK_CHECK(vkCreateBuffer(device, &bci, nullptr, &buffers[i]));

        VkMemoryRequirements mreq;
        vkGetBufferMemoryRequirements(device, buffers[i], &mreq);
        uint32_t mem_type = find_memory_type(
            phys, mreq.memoryTypeBits,
            VK_MEMORY_PROPERTY_HOST_VISIBLE_BIT | VK_MEMORY_PROPERTY_HOST_COHERENT_BIT);
        if (mem_type == UINT32_MAX) {
            fprintf(stderr, "FAIL: no host-visible+coherent memory type\n");
            return 1;
        }
        VkMemoryAllocateInfo mai{};
        mai.sType = VK_STRUCTURE_TYPE_MEMORY_ALLOCATE_INFO;
        mai.allocationSize = mreq.size;
        mai.memoryTypeIndex = mem_type;
        VK_CHECK(vkAllocateMemory(device, &mai, nullptr, &memories[i]));
        VK_CHECK(vkBindBufferMemory(device, buffers[i], memories[i], 0));
    }

    // Fill a[] and b[]
    {
        void *ptr;
        VK_CHECK(vkMapMemory(device, memories[0], 0, buf_size, 0, &ptr));
        float *a = static_cast<float *>(ptr);
        for (uint32_t i = 0; i < N; i++) a[i] = static_cast<float>(i);
        vkUnmapMemory(device, memories[0]);

        VK_CHECK(vkMapMemory(device, memories[1], 0, buf_size, 0, &ptr));
        float *b = static_cast<float *>(ptr);
        for (uint32_t i = 0; i < N; i++) b[i] = static_cast<float>(i) * 2.0f;
        vkUnmapMemory(device, memories[1]);
    }

    // --- Descriptor pool + set ---
    VkDescriptorPoolSize pool_size{};
    pool_size.type = VK_DESCRIPTOR_TYPE_STORAGE_BUFFER;
    pool_size.descriptorCount = 3;
    VkDescriptorPoolCreateInfo dpci{};
    dpci.sType = VK_STRUCTURE_TYPE_DESCRIPTOR_POOL_CREATE_INFO;
    dpci.maxSets = 1;
    dpci.poolSizeCount = 1;
    dpci.pPoolSizes = &pool_size;
    VkDescriptorPool pool;
    VK_CHECK(vkCreateDescriptorPool(device, &dpci, nullptr, &pool));

    VkDescriptorSetAllocateInfo dsai{};
    dsai.sType = VK_STRUCTURE_TYPE_DESCRIPTOR_SET_ALLOCATE_INFO;
    dsai.descriptorPool = pool;
    dsai.descriptorSetCount = 1;
    dsai.pSetLayouts = &dsl;
    VkDescriptorSet dset;
    VK_CHECK(vkAllocateDescriptorSets(device, &dsai, &dset));

    VkDescriptorBufferInfo buf_infos[3];
    VkWriteDescriptorSet writes[3]{};
    for (int i = 0; i < 3; i++) {
        buf_infos[i] = {buffers[i], 0, buf_size};
        writes[i].sType = VK_STRUCTURE_TYPE_WRITE_DESCRIPTOR_SET;
        writes[i].dstSet = dset;
        writes[i].dstBinding = i;
        writes[i].descriptorCount = 1;
        writes[i].descriptorType = VK_DESCRIPTOR_TYPE_STORAGE_BUFFER;
        writes[i].pBufferInfo = &buf_infos[i];
    }
    vkUpdateDescriptorSets(device, 3, writes, 0, nullptr);

    // --- Command buffer: dispatch ---
    VkCommandPoolCreateInfo cpci2{};
    cpci2.sType = VK_STRUCTURE_TYPE_COMMAND_POOL_CREATE_INFO;
    cpci2.queueFamilyIndex = compute_qf;
    VkCommandPool cmd_pool;
    VK_CHECK(vkCreateCommandPool(device, &cpci2, nullptr, &cmd_pool));

    VkCommandBufferAllocateInfo cbai{};
    cbai.sType = VK_STRUCTURE_TYPE_COMMAND_BUFFER_ALLOCATE_INFO;
    cbai.commandPool = cmd_pool;
    cbai.level = VK_COMMAND_BUFFER_LEVEL_PRIMARY;
    cbai.commandBufferCount = 1;
    VkCommandBuffer cmd;
    VK_CHECK(vkAllocateCommandBuffers(device, &cbai, &cmd));

    VkCommandBufferBeginInfo cbbi{};
    cbbi.sType = VK_STRUCTURE_TYPE_COMMAND_BUFFER_BEGIN_INFO;
    cbbi.flags = VK_COMMAND_BUFFER_USAGE_ONE_TIME_SUBMIT_BIT;
    VK_CHECK(vkBeginCommandBuffer(cmd, &cbbi));

    vkCmdBindPipeline(cmd, VK_PIPELINE_BIND_POINT_COMPUTE, pipeline);
    vkCmdBindDescriptorSets(cmd, VK_PIPELINE_BIND_POINT_COMPUTE, pipeline_layout,
                             0, 1, &dset, 0, nullptr);
    vkCmdPushConstants(cmd, pipeline_layout, VK_SHADER_STAGE_COMPUTE_BIT, 0,
                        sizeof(uint32_t), &N);
    vkCmdDispatch(cmd, (N + 63) / 64, 1, 1);

    VK_CHECK(vkEndCommandBuffer(cmd));

    VkSubmitInfo submit{};
    submit.sType = VK_STRUCTURE_TYPE_SUBMIT_INFO;
    submit.commandBufferCount = 1;
    submit.pCommandBuffers = &cmd;
    VK_CHECK(vkQueueSubmit(queue, 1, &submit, VK_NULL_HANDLE));
    VK_CHECK(vkQueueWaitIdle(queue));
    printf("PASS: dispatch + queue wait idle\n");

    // --- Verify c[i] == a[i] + b[i] ---
    void *ptr;
    VK_CHECK(vkMapMemory(device, memories[2], 0, buf_size, 0, &ptr));
    float *c = static_cast<float *>(ptr);
    bool ok = true;
    for (uint32_t i = 0; i < N; i++) {
        float expected = static_cast<float>(i) + static_cast<float>(i) * 2.0f;
        if (c[i] != expected) {
            fprintf(stderr, "FAIL: c[%u] = %f, expected %f\n", i, c[i], expected);
            ok = false;
            break;
        }
    }
    vkUnmapMemory(device, memories[2]);

    if (!ok) {
        return 1;
    }
    printf("PASS: readback verified (c[i] == a[i] + b[i] for all %u elements)\n",
           N);
    printf("=== ALL CHECKS PASSED ===\n");

    // Cleanup (best-effort; process exit will reclaim everything anyway).
    vkDestroyCommandPool(device, cmd_pool, nullptr);
    vkDestroyDescriptorPool(device, pool, nullptr);
    for (int i = 0; i < 3; i++) {
        vkDestroyBuffer(device, buffers[i], nullptr);
        vkFreeMemory(device, memories[i], nullptr);
    }
    vkDestroyPipeline(device, pipeline, nullptr);
    vkDestroyPipelineLayout(device, pipeline_layout, nullptr);
    vkDestroyDescriptorSetLayout(device, dsl, nullptr);
    vkDestroyShaderModule(device, shader, nullptr);
    vkDestroyDevice(device, nullptr);
    vkDestroyInstance(instance, nullptr);
    return 0;
}
