// swift-tools-version: 6.0
//
// SuperDictate — a Swift push-to-talk dictation app
// for macOS Apple Silicon. Native AppKit / AVFoundation, FluidAudio
// driving Parakeet TDT v3 on the Apple Neural Engine. macOS 14
// (Sonoma) minimum. The Hardened Runtime microphone entitlement
// (`com.apple.security.device.audio-input` in `entitlements.plist`)
// is what Tahoe 26 checks before exposing the app in Privacy &
// Security → Microphone; on macOS 14–25 the legacy sandbox key
// (`com.apple.security.device.microphone`) is the fallback. Both
// ship in the same build so a single notarised binary works
// across the supported range.
import PackageDescription

let package = Package(
    name: "Parakey",
    platforms: [
        .macOS("14.0"),
    ],
    products: [
        .executable(name: "Parakey", targets: ["Parakey"]),
    ],
    dependencies: [],
    targets: [
        .target(
            name: "whisper_cpp",
            exclude: [
                "ggml-cpu/arch/arm",
                "ggml-cpu/arch/riscv",
                "ggml-cpu/arch/powerpc",
                "ggml-cpu/arch/s390",
                "ggml-cpu/arch/wasm",
                "ggml-cpu/arch/loongarch",
                "ggml-cpu/spacemit",
                // Vendored by scripts/vendor-whisper-cpp.sh (Task 1 of the
                // intel-mac-vulkan-backend plan) but still excluded here:
                // this target has no `sources:` allowlist, so SwiftPM
                // implicitly compiles every .cpp under the target
                // directory, and ggml-vulkan.cpp needs Vulkan SDK header
                // search paths and MoltenVK linker settings this target
                // doesn't have yet (Task 3's job: "statically link
                // MoltenVK and add Vulkan build configuration to
                // Package.swift"). Task 5 removes this exclude entry once
                // that's in place.
                //
                // ggml-vulkan.cpp's own `#include "ggml-vulkan-shaders.hpp"`
                // (upstream's CMake-generated byte-array-embedding header,
                // which this project deliberately never produces — see the
                // vendoring script's SPIR-V section) is already satisfied
                // as of Task 2: swift/Sources/whisper_cpp/ggml-vulkan-shaders.hpp
                // (+ .cpp) is a drop-in replacement that loads each
                // shader's `.spv` bytes from
                // swift/Sources/whisper_cpp/vulkan-shaders/ at runtime
                // instead of compiling them in — see
                // include/ggml-vulkan-shaders-runtime.h for the mechanism.
                // Those two generated files (plus
                // ggml-vulkan-shaders-runtime.cpp, the hand-written loader
                // implementation) have no Vulkan-SDK dependency of their
                // own, so — unlike ggml-vulkan.cpp itself — they are NOT
                // excluded below and already compile as part of this
                // target today (verified via `swift build -c debug` on
                // the real Mac).
                //
                // Task 5, when wiring Vulkan into WhisperEngine: call
                // ggml_vk_shaders_set_directory() (declared in
                // include/ggml-vulkan-shaders-runtime.h) with the
                // resolved Contents/Resources/vulkan-shaders/ bundle path
                // BEFORE ggml_backend_vk_init() / any Vulkan backend init
                // — this is not optional. Skipping it does not gracefully
                // fall back to CPU: every one of the ~1785 shader
                // symbols silently resolves to a null pointer + zero
                // length (logged to stderr, not thrown), which flows
                // straight into vk::ShaderModuleCreateInfo and will most
                // likely surface as a Vulkan/MoltenVK-level crash or
                // validation error deep inside ggml-vulkan.cpp instead of
                // a clean, catchable failure at the Swift boundary.
                "ggml-vulkan.cpp",
                // Raw .spv binaries (48MB, 1785 files) pre-compiled by
                // scripts/vendor-whisper-cpp.sh. Excluded (not source,
                // not Swift) so SwiftPM neither tries to compile them nor
                // auto-bundles them as a resource — this project loads
                // them by explicit file path at runtime instead (see the
                // vendoring script's SPIR-V section; per the parent
                // plan's global constraints, `resources:` must never
                // reference this directory). Same rationale as the
                // menubar-PNG precedent in the Parakey target below: keep
                // SwiftPM's own resource-bundling mechanism out of it
                // entirely. This entry is permanent, unlike the one above.
                "vulkan-shaders",
            ],
            cSettings: [
                .define("GGML_USE_ACCELERATE"),
                .define("GGML_USE_CPU"),
                .define("GGML_USE_BLAS"),
                .define("GGML_BLAS_USE_ACCELERATE"),
                .define("ACCELERATE_NEW_LAPACK"),
                .define("ACCELERATE_LAPACK_ILP64"),
                // Metal backend is REGISTERED here so it shows up in
                // ggml_backend_reg_count()/whisper_print_system_info(),
                // but it is NOT enabled by default: WhisperEngine.init
                // hardcodes params.use_gpu = false, so ggml never
                // actually schedules work on it until a later task adds
                // a user-facing toggle. GGML_METAL_EMBED_LIBRARY matches
                // the pre-generated ggml-metal-embed.cpp checked in by
                // scripts/vendor-whisper-cpp.sh (see that script for why
                // the shader is embedded as a C string instead of a
                // SwiftPM resource/build step).
                .define("GGML_USE_METAL"),
                .define("GGML_METAL_EMBED_LIBRARY"),
                // Vulkan backend define (Task 3 of the intel-mac-vulkan-backend
                // plan). This is what ggml-backend-reg.cpp's #ifdef
                // GGML_USE_VULKAN gates registration on (calling
                // ggml_backend_vk_reg(), declared in ggml-vulkan.h and defined
                // in ggml-vulkan.cpp). ggml-vulkan.cpp itself is still excluded
                // above as of this task, so registration will fail to link
                // until Task 5 removes that exclude — building this target
                // alone (a static archive, not a final executable) does not
                // require every symbol to resolve, so that's expected and
                // fine at this stage. The header search path below points at
                // Homebrew's vulkan-headers package (vulkan/vulkan_core.h,
                // vulkan/vulkan.hpp) that ggml-vulkan.cpp/.h include; see
                // vulkan-spike/Package.swift for the proven-working reference
                // this was transcribed from.
                .define("GGML_USE_VULKAN"),
                .define("GGML_VERSION", to: "\"080bbbe8\""),
                .define("GGML_COMMIT", to: "\"080bbbe85230f624f0b52127f1ae1218247989f9\""),
                .define("WHISPER_VERSION", to: "\"080bbbe8\""),
                .headerSearchPath("."),
                .headerSearchPath("ggml-cpu"),
                // ggml-metal-context.m/ggml-metal-device.m are upstream
                // Objective-C written for manual retain/release (they
                // guard their explicit `release` calls with
                // `#if !__has_feature(objc_arc)` and cast raw `void *`
                // Metal handles to `id<...>` without `__bridge`).
                // SwiftPM compiles .m sources under ARC by default, which
                // makes both of those patterns compile errors, so ARC is
                // disabled for the whole target to match upstream's own
                // (non-ARC) build. Harmless no-op for the plain C/C++
                // sources also built with these flags. The vulkan-headers
                // -I flag is Task 3's addition (see the GGML_USE_VULKAN
                // comment above). Uses Homebrew's `opt/` symlink (not the
                // versioned Cellar path the throwaway vulkan-spike package
                // used) so this doesn't break on the next `brew upgrade`;
                // resolves to the same files the spike proved work.
                .unsafeFlags([
                    "-mavx2", "-mfma", "-mf16c", "-mbmi2", "-msse4.2", "-fno-objc-arc",
                    "-I/usr/local/opt/vulkan-headers/include",
                ]),
            ],
            cxxSettings: [
                .define("GGML_USE_ACCELERATE"),
                .define("GGML_USE_CPU"),
                .define("GGML_USE_BLAS"),
                .define("GGML_BLAS_USE_ACCELERATE"),
                .define("ACCELERATE_NEW_LAPACK"),
                .define("ACCELERATE_LAPACK_ILP64"),
                // See the matching comment in cSettings above.
                .define("GGML_USE_METAL"),
                .define("GGML_METAL_EMBED_LIBRARY"),
                // See the GGML_USE_VULKAN comment in cSettings above.
                .define("GGML_USE_VULKAN"),
                .define("GGML_VERSION", to: "\"080bbbe8\""),
                .define("GGML_COMMIT", to: "\"080bbbe85230f624f0b52127f1ae1218247989f9\""),
                .define("WHISPER_VERSION", to: "\"080bbbe8\""),
                .headerSearchPath("."),
                .headerSearchPath("ggml-cpu"),
                .unsafeFlags([
                    "-mavx2", "-mfma", "-mf16c", "-mbmi2", "-msse4.2",
                    "-I/usr/local/opt/vulkan-headers/include",
                ]),
            ],
            linkerSettings: [
                .linkedFramework("Accelerate"),
                .linkedFramework("Metal"),
                .linkedFramework("MetalKit"),
                .linkedFramework("Foundation"),
                // Vulkan/MoltenVK (Task 3 of the intel-mac-vulkan-backend
                // plan). Frameworks + libraries below are the exact set
                // vulkan-spike/Package.swift proved sufficient for
                // statically-linked MoltenVK on this machine: `otool -L`
                // on the spike's built binary showed only these system
                // frameworks plus libc++/libobjc/libSystem — no Homebrew
                // dylib paths — and the binary ran correctly with
                // Homebrew's Vulkan install hidden, confirming no runtime
                // dependency on it. IOSurface/IOKit/AppKit/QuartzCore/
                // CoreFoundation/CoreGraphics are additional to the
                // Metal/Foundation frameworks already linked above for the
                // Metal backend.
                .linkedFramework("IOSurface"),
                .linkedFramework("IOKit"),
                .linkedFramework("AppKit"),
                .linkedFramework("QuartzCore"),
                .linkedFramework("CoreFoundation"),
                .linkedFramework("CoreGraphics"),
                .linkedLibrary("objc"),
                .linkedLibrary("c++"),
                // Statically link MoltenVK itself (the actual Vulkan
                // implementation) rather than -lMoltenVK/-lvulkan, which
                // would resolve to Homebrew's dylibs and the Vulkan
                // loader/ICD mechanism at runtime. Passing the .a path
                // directly avoids any ambiguity between the .a and .dylib
                // Homebrew installs side by side in the same lib dir. Uses
                // Homebrew's `opt/` symlink rather than the versioned
                // Cellar path vulkan-spike/Package.swift used, for the same
                // brew-upgrade-resilience reason as the cSettings -I flag
                // above; resolves to the identical file the spike proved
                // works (confirmed via `ls -l`/`lipo -info` on the real Mac).
                .unsafeFlags([
                    "/usr/local/opt/molten-vk/lib/libMoltenVK.a",
                ]),
            ]
        ),
        .executableTarget(
            name: "Parakey",
            dependencies: ["whisper_cpp"]
            // No `resources:` here on purpose. SwiftPM bundles them as
            // a `<Package>_<Target>.bundle` directory next to the
            // executable, which `codesign --deep` won't accept as a
            // signable component because it lacks Info.plist. Instead,
            // the menubar PNGs are copied into Contents/Resources/ by
            // dev-run.sh and ship-swift.sh — the canonical .app layout
            // where Bundle.main finds them via the standard search
            // path. Source PNGs live in swift/Resources/ at the repo
            // root, NOT in the SwiftPM target, so SwiftPM never sees them.
        ),
    ],
    cLanguageStandard: .c17,
    cxxLanguageStandard: .cxx17
)
