#!/usr/bin/env python3
"""Turn upstream vulkan-shaders-gen's aggregate-mode header (pure `extern`
declarations, no compiled-in byte arrays — see the call site in
scripts/vendor-parakeet-cpp.sh's Vulkan section for how it's produced) into
this project's runtime SPIR-V loader sources:

  swift/Sources/parakeet_cpp/upstream/ggml-vulkan/ggml-vulkan-shaders.hpp
      — declares the exact same identifiers ggml-vulkan.cpp's (heavily
      macro-generated) ggml_vk_create_pipeline(...) call sites already
      reference, backed by ggml_vk_shaders_detail::lazy_data/lazy_len proxy
      objects (declared in ggml-vulkan-shaders-runtime.h) instead of
      upstream's compiled-in byte arrays.
  swift/Sources/parakeet_cpp/upstream/ggml-vulkan/ggml-vulkan-shaders.cpp
      — defines them.

This is a direct, ggml-version-independent port of the mechanism this fork
already proved for whisper.cpp's Vulkan backend (commit b0ab800,
"Load Vulkan SPIR-V shaders from bundled resource files at runtime") —
parakeet.cpp's own pinned ggml v0.13.0 ships the identical
vulkan-shaders-gen.cpp write_output_files() shape, so this script is
unmodified logic, only the doc comments/paths below were updated for this
project's parakeet_cpp target instead of whisper_cpp.

Why this works at all: vulkan-shaders-gen.cpp's write_output_files()
declares every shader symbol as `extern const uint64_t <name>_len;` /
`extern const unsigned char <name>_data[];` in the header regardless of
mode, and only *emits the byte data* into the paired .cpp when --source is
given (see string_to_spv()'s `input_filepath == ""` branch upstream) — so
running it with --output-dir/--target-hpp but no --source (a separate,
cheap invocation from the real per-.comp --source compiles scripts/
vendor-parakeet-cpp.sh's Vulkan section already does to produce the real
.spv corpus) produces a header with the ground-truth set of identifier
names and zero glslc/Vulkan-SDK dependency for this step, and an
essentially-empty .cpp we don't use.

There are three shapes of declaration in that ground-truth header (verified
by reading vulkan-shaders-gen.cpp's write_output_files() directly — see
that function for the authoritative definitions this script mirrors):
  1. simple:   extern const uint64_t <name>_len;
               extern const unsigned char <name>_data[];
     — one pair per compiled .spv file (154 top-level .comp files expand to
     several hundred typed/quantization variants as of parakeet.cpp's
     pinned ggml v0.13.0).
  2. op aggregates: extern const void * <op>_data[2][2][2];  (5 ops: add,
     sub, mul, div, add_rms) — each cell is <op>_f32|f16_f32|f16_f32|f16
     (nested loop over the two type suffixes, 3 levels deep).
  3. arr_dmmv aggregates: extern const void * arr_dmmv[_id]_<mid>_data[3];
     — each cell is mul_mat_vec[_id]_<mid>[, _subgroup, _subgroup_no_shmem].

This script derives (2)'s naming purely from the fixed suffix/loop shape
upstream's write_output_files() uses (small and stable enough to hardcode),
and (3)'s naming by string manipulation on the aggregate declaration itself
(so it needs no knowledge of vulkan-shaders-gen's tname/type_names loop —
just the observation that the declared array name IS the suffix appended
to "mul_mat_vec[_id]_").
"""
import re
import sys

SIMPLE_RE = re.compile(r"^extern const uint64_t ([A-Za-z0-9_]+)_len;$")
OP_DATA_RE = re.compile(r"^extern const void \* (add|sub|mul|div|add_rms)_data\[2\]\[2\]\[2\];$")
ARR_DATA_RE = re.compile(r"^extern const void \* arr_dmmv_(id_)?([A-Za-z0-9_]+)_data\[3\];$")

SUFFIXES = ["_f32", "_f16"]


def main():
    if len(sys.argv) != 4:
        print(f"usage: {sys.argv[0]} <ground-truth-hpp> <out-hpp> <out-cpp>", file=sys.stderr)
        sys.exit(1)
    src_path, out_hpp_path, out_cpp_path = sys.argv[1:4]

    with open(src_path) as f:
        lines = [l.rstrip("\n") for l in f]

    simple_names = []
    ops = []
    arrs = []  # (full_name, is_id, mid)

    for line in lines:
        m = SIMPLE_RE.match(line)
        if m:
            simple_names.append(m.group(1))
            continue
        m = OP_DATA_RE.match(line)
        if m:
            ops.append(m.group(1))
            continue
        m = ARR_DATA_RE.match(line)
        if m:
            is_id = m.group(1) is not None
            mid = m.group(2)
            full = ("arr_dmmv_id_" if is_id else "arr_dmmv_") + mid
            arrs.append((full, is_id, mid))
            continue

    simple_names.sort()
    ops.sort()
    arrs.sort()

    if not simple_names:
        print("error: no simple shader symbols found in ground-truth header "
              "— parsing broke, or vulkan-shaders-gen's write_output_files() "
              "format changed upstream", file=sys.stderr)
        sys.exit(1)

    # ---- header ----
    hdr = []
    hdr.append("// GENERATED FILE. Do not hand-edit.")
    hdr.append("//")
    hdr.append("// Regenerated by scripts/gen-vulkan-shader-runtime.py, invoked from")
    hdr.append("// scripts/vendor-parakeet-cpp.sh's Vulkan section. See that script for how")
    hdr.append("// the ground-truth input (vulkan-shaders-gen's own aggregate-mode header")
    hdr.append("// output) is produced, and this script's own module docstring for the")
    hdr.append("// three declaration shapes it turns into lazy, runtime-file-loaded")
    hdr.append("// symbols instead of upstream's compiled-in byte arrays.")
    hdr.append("#pragma once")
    hdr.append("")
    hdr.append('#include "ggml-vulkan-shaders-runtime.h"')
    hdr.append("")
    hdr.append("using ggml_vk_shaders_detail::lazy_data;")
    hdr.append("using ggml_vk_shaders_detail::lazy_len;")
    hdr.append("")
    for name in simple_names:
        hdr.append(f"extern const lazy_len {name}_len;")
        hdr.append(f"extern const lazy_data {name}_data;")
        hdr.append("")
    for op in ops:
        hdr.append(f"extern const lazy_data {op}_data[2][2][2];")
        hdr.append(f"extern const lazy_len {op}_len[2][2][2];")
    if ops:
        hdr.append("")
    for full, is_id, mid in arrs:
        hdr.append(f"extern const lazy_data {full}_data[3];")
        hdr.append(f"extern const lazy_len {full}_len[3];")

    # ---- cpp ----
    cpp = []
    cpp.append("// GENERATED FILE. Do not hand-edit. See ggml-vulkan-shaders.hpp for how.")
    cpp.append('#include "ggml-vulkan-shaders.hpp"')
    cpp.append("")
    for name in simple_names:
        cpp.append(f'const lazy_len {name}_len{{"{name}"}};')
        cpp.append(f'const lazy_data {name}_data{{"{name}"}};')
    cpp.append("")
    for op in ops:
        data_rows = []
        len_rows = []
        for t0 in SUFFIXES:
            data_cols = []
            len_cols = []
            for t1 in SUFFIXES:
                data_inner = []
                len_inner = []
                for t2 in SUFFIXES:
                    name = f"{op}{t0}{t1}{t2}"
                    data_inner.append(f'lazy_data("{name}")')
                    len_inner.append(f'lazy_len("{name}")')
                data_cols.append("{" + ", ".join(data_inner) + "}")
                len_cols.append("{" + ", ".join(len_inner) + "}")
            data_rows.append("{" + ", ".join(data_cols) + "}")
            len_rows.append("{" + ", ".join(len_cols) + "}")
        cpp.append(f"const lazy_data {op}_data[2][2][2] = {{{', '.join(data_rows)}}};")
        cpp.append(f"const lazy_len {op}_len[2][2][2] = {{{', '.join(len_rows)}}};")
    cpp.append("")
    for full, is_id, mid in arrs:
        base = ("mul_mat_vec_id_" if is_id else "mul_mat_vec_") + mid
        members = [base, base + "_subgroup", base + "_subgroup_no_shmem"]
        data_members = ", ".join(f'lazy_data("{m}")' for m in members)
        len_members = ", ".join(f'lazy_len("{m}")' for m in members)
        cpp.append(f"const lazy_data {full}_data[3] = {{{data_members}}};")
        cpp.append(f"const lazy_len {full}_len[3] = {{{len_members}}};")

    with open(out_hpp_path, "w") as f:
        f.write("\n".join(hdr) + "\n")
    with open(out_cpp_path, "w") as f:
        f.write("\n".join(cpp) + "\n")

    print(f"gen-vulkan-shader-runtime.py: {len(simple_names)} simple + "
          f"{len(ops)} op-aggregate + {len(arrs)} arr_dmmv-aggregate shader "
          f"symbols", file=sys.stderr)


if __name__ == "__main__":
    main()
