#!/bin/bash
# scripts/spike-embed-spirv.sh — SPIKE ONLY. Not part of the real
# vendoring pipeline (see vendor-whisper-cpp.sh for that). This proves
# Unknown 1 from the intel-mac-vulkan-backend spike: that GLSL compute
# shaders can be compiled to SPIR-V with glslc and embedded as checked-in
# C++ byte arrays, analogous to how ggml-metal-embed.cpp embeds the
# merged Metal shader source as a `const char[]` at vendor time instead
# of relying on a SwiftPM build-time step (SwiftPM has no direct
# equivalent of a CMake custom build command).
#
# This script must run on macOS with `glslc` on PATH (from Homebrew's
# `shaderc` package). It is NOT invoked automatically by any build step;
# run it by hand and commit the regenerated
# swift/Sources/VulkanSpike/spirv_embed.h when the spike shader source
# changes.
#
# Usage: scripts/spike-embed-spirv.sh
set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
SPIKE_DIR="$ROOT_DIR/swift/Sources/VulkanSpike"
OUT_HEADER="$SPIKE_DIR/spirv_embed.h"
WORK_DIR="$(mktemp -d)"
trap 'rm -rf "$WORK_DIR"' EXIT

command -v glslc >/dev/null || { echo "glslc not found on PATH (brew install shaderc)" >&2; exit 1; }

# 1) Compile our own trivial test shader directly with glslc.
glslc -fshader-stage=compute --target-env=vulkan1.2 \
    -o "$WORK_DIR/vecadd.spv" \
    "$SPIKE_DIR/shaders/vecadd.comp"

# 2) Also compile a REAL ggml-vulkan shader, using the REAL upstream
# vulkan-shaders-gen tool (not glslc directly — real ggml shaders use
# preprocessor defines like A_TYPE/D_TYPE that vulkan-shaders-gen
# supplies per type-variant; hand-invoking glslc on them directly would
# require reverse-engineering that define set). This proves the actual
# upstream shader *sources* are consumable by our toolchain — i.e. that
# whatever mechanism the real implementation adopts (SwiftPM plugin vs.
# vendor-time generation) is compiling genuine ggml SPIR-V, not just our
# own placeholder shader.
#
# Prerequisite (not automated here — do this once, by hand, if
# GGML_VULKAN_SHADERS_GEN or GGML_VULKAN_SHADER_SRC_DIR aren't set):
#   git clone https://github.com/ggml-org/whisper.cpp /tmp/ggml-vk-src
#   git -C /tmp/ggml-vk-src checkout 080bbbe85230f624f0b52127f1ae1218247989f9
#   cmake -S /tmp/ggml-vk-src -B /tmp/ggml-vk-src/build -DGGML_VULKAN=ON
#   cmake --build /tmp/ggml-vk-src/build --target vulkan-shaders-gen
if [[ -n "${GGML_VULKAN_SHADERS_GEN:-}" && -n "${GGML_VULKAN_SHADER_SRC_DIR:-}" ]]; then
    "$GGML_VULKAN_SHADERS_GEN" \
        --glslc "$(command -v glslc)" \
        --source "$GGML_VULKAN_SHADER_SRC_DIR/copy.comp" \
        --output-dir "$WORK_DIR" \
        --target-hpp "$WORK_DIR/ggml-vulkan-shaders.hpp" \
        --target-cpp "$WORK_DIR/copy.comp.cpp"
    cp "$WORK_DIR/cpy_f32_f32.spv" "$WORK_DIR/real_ggml_cpy_f32_f32.spv"
    HAVE_REAL_SHADER=1
else
    echo "GGML_VULKAN_SHADERS_GEN/GGML_VULKAN_SHADER_SRC_DIR not set — skipping real-shader embed (vecadd-only run)." >&2
    HAVE_REAL_SHADER=0
fi

# 3) Emit a C++ header with each .spv's bytes as a `const uint32_t[]`
# array (SPIR-V is natively a stream of 32-bit words — this is exactly
# what vkShaderModuleCreateInfo::pCode expects, so no repacking is
# needed at load time, unlike the Metal embed's raw-byte C string).
emit_array() {
    local spv_file="$1" var_name="$2"
    local size_bytes
    size_bytes=$(wc -c < "$spv_file")
    echo "// $spv_file ($size_bytes bytes)"
    echo "static const uint32_t ${var_name}[] = {"
    # od reads 4-byte little-endian words as hex, one per line via -An -tx4;
    # SPIR-V is defined little-endian on all platforms we target (Vulkan
    # spec 2.2.1), and x86_64/arm64 macOS are both little-endian, so this
    # is a direct byte-for-byte reinterpretation, not a real endian swap.
    od -An -tx4 -v "$spv_file" | awk '{for (i=1;i<=NF;i++) printf "0x%s,\n", $i}'
    echo "};"
    echo "static const size_t ${var_name}_len = sizeof(${var_name}) / sizeof(${var_name}[0]);"
    echo
}

{
    echo "// GENERATED FILE — regenerated by scripts/spike-embed-spirv.sh (never hand-edit)."
    echo "// SPIKE ONLY: see swift/Sources/VulkanSpike/main.cpp for how this is consumed."
    echo "#pragma once"
    echo "#include <cstdint>"
    echo "#include <cstddef>"
    echo
    emit_array "$WORK_DIR/vecadd.spv" "g_vecadd_spv"
    if [[ "$HAVE_REAL_SHADER" == "1" ]]; then
        echo "#define VULKAN_SPIKE_HAVE_REAL_GGML_SHADER 1"
        emit_array "$WORK_DIR/real_ggml_cpy_f32_f32.spv" "g_real_ggml_cpy_f32_f32_spv"
    else
        echo "#define VULKAN_SPIKE_HAVE_REAL_GGML_SHADER 0"
    fi
} > "$OUT_HEADER"

echo "Wrote $OUT_HEADER"
